### PR TITLE
Pull request BurkinaFaso 2017-18(2) JW 20210623

### PR DESCRIPTION
**Pull request by jianingwwww**
- adjust the definition of skilled provider to align with the public data

### CODE REVIEW

**Comment by jianingwwww** [comment]
#9

**Comment by robin-wang** [comment]
Hi Jianing, thanks for your update based on our discussions in #9 
I have tried to replicate your results based on the corrected version of raw data (suffix 2017-18), but no quality checking indicators had been created. Could you please investigaate?

Screenshot 2021-06-23 at 12 45 40 PM

**Comment by jianingwwww** [comment]
Hi @robin-wang , sorry for this mistake! I found there was one line in the MAIN branch different from the codes on my end and I made the commit to change it,  which should be ok now. Please tell me if it still doesn't work for you~

**Comment by robin-wang** [comment]
Discrepency addressed based on JW's latest commit. @jianingwwww  Great work!
#5 


Screenshot 2021-06-24 at 10 08 33 PM

**Comment by robin-wang** [comment]
Closed.

**Pull request merged**
