### PR TITLE
Pull request Liberia 2009 JW 210616

### PR DESCRIPTION
**Pull request by jianingwwww**
-replace the surveyid to align with the surveyid in the DHS.DTA

### CODE REVIEW

**Comment by jianingwwww** [comment]
The quality control results are shown above. I have checked the process of generating c_ITN and c_anc_ski, no problem found.

**Comment by robin-wang** [comment]
> 
> 
> The quality control results are shown above. I have checked the process of generating c_ITN and c_anc_ski, no problem found.

Thanks Jianing!
@wengxyu1030 Hey Aline, does this look a bit off?

**Comment by wengxyu1030** [comment]
Thanks @jianingwwww and @robin-wang , I am wondering is that because the definition of values for variable m10 in this survey is different? Can you tab m10 and share the screenshot in the conversation?

**Comment by jianingwwww** [comment]
> Thanks @jianingwwww and @robin-wang , I am wondering is that because the definition of values for variable m10 in this survey is different? Can you tab m10 and share the screenshot in the conversation?

1926e50a570922a78634493230bf2ec

Hi @wengxyu1030 ，I assume you are referring to ml0 used to generate c_ITN (m10 not available in the raw data)?  I tab ml0 and it appears to be no exception to the definition of bednet.

**Comment by wengxyu1030** [comment]
Thanks @jianingwwww , this is clear to me I have no further questions.

**Comment by robin-wang** [comment]
Liberia 2009 closed. Pull request confirmed.

**Comment by robin-wang** [comment]
#23

**Pull request merged**
