### PR TITLE
Pull request Liberia 2016 JW 210616

### PR DESCRIPTION
**Pull request by jianingwwww**
- replace the surveyid to align with the surveyid in the DHS.DTA
- generate variables relating to vaccination

### CODE REVIEW

**Comment by jianingwwww** [comment]
d7ae0d06ff663f6d6f8141fe81f825b
Here is the quality control result. I have checked all raw data of Liberia2016, and both ind and child dta have dpt variables h3, h5, h7 (dpt1, dpt2, dpt3). However, all dpt variables are missing values so c_dpt1/2/3 could not be generated, even though there exist values in the public data. The 0 in the c_fullimm is also due to the absence of the dpt values. Are there any other changes I should make? Thanks in advance!


f3cd3325d9d1da53a4023dd4a5b64d1
9d31514fcf2402a8ee0301c1c5f0362
91a23945903d7421c5e693fd16dd70c

**Comment by robin-wang** [comment]
@jianingwwww Thanks Jianing! 
@wengxyu1030 I feel this case should be marked for the noted mismatch, but for the moment, we should move on? Cheers!

**Comment by wengxyu1030** [comment]
Thanks, @jianingwwww and @robin-wang , I agree we should move on but do keep this in mind and in the documentation for future references.

**Comment by robin-wang** [comment]
Manually merged differences in quality control file. 
Note the possibility of further changes with regard to the missing indicators; move on to Madagascar.

#21

**Pull request merged**
