### PR TITLE
Pull request Angola 2006-07 JW 20210603

### PR DESCRIPTION
**Pull request by jianingwwww**
- change the file name from DHS to MIS
- delete rename lines
- generate survey-specific year variable

### CODE REVIEW

**Comment by wengxyu1030** [comment]
image


Thanks @imarabbit , nice catch on the year variable. 

However, based on the quality control result, there should be available information for c_sba (as the screenshot above), could you check again?

**Comment by wengxyu1030** [comment]
Please rebase and solve the conflict before pulling request again, many thanks!

**Comment by jianingwwww** [comment]
> image
> 
> Thanks @imarabbit , nice catch on the year variable.
> 
> However, based on the quality control result, there should be available information for c_sba (as the screenshot above), could you check again?

Hi @wengxyu1030 , I checked the delivery care do file and found that c_sba should not be generated (the corresponding code is "gen c_sba = . "). However, I haven't figured out why c_sba would show in the quality control result, very sorry for that!

**Comment by robin-wang** [comment]
> > image
> > Thanks @imarabbit , nice catch on the year variable.
> > However, based on the quality control result, there should be available information for c_sba (as the screenshot above), could you check again?
> 
> Hi @wengxyu1030 , I checked the delivery care do file and found that c_sba should not be generated (the corresponding code is "gen c_sba = . "). However, I haven't figured out why c_sba would show in the quality control result, very sorry for that!

If still not resolved at this stage, please reach out to me directly. I'll see what I can do to help.

**Comment by wengxyu1030** [comment]
> > image
> > Thanks @imarabbit , nice catch on the year variable.
> > However, based on the quality control result, there should be available information for c_sba (as the screenshot above), could you check again?
> 
> Hi @wengxyu1030 , I checked the delivery care do file and found that c_sba should not be generated (the corresponding code is "gen c_sba = . "). However, I haven't figured out why c_sba would show in the quality control result, very sorry for that!

Dear @imarabbit , thanks for your response. The c_sba might be missing in most of the cases, so the template is coded as "gen c_sba = .". However, for this Angola 2006-07 MIS survey, the c_sba data is available according to the public data. The quality checking file column value_dhs is the publicly available indicator statistics generated by the USAID, which conducted the DHS. Hope my clarification makes sense to you.

**Comment by jianingwwww** [comment]
> > > image
> > > Thanks @imarabbit , nice catch on the year variable.
> > > However, based on the quality control result, there should be available information for c_sba (as the screenshot above), could you check again?
> > 
> > 
> > Hi @wengxyu1030 , I checked the delivery care do file and found that c_sba should not be generated (the corresponding code is "gen c_sba = . "). However, I haven't figured out why c_sba would show in the quality control result, very sorry for that!
> 
> Dear @imarabbit , thanks for your response. The c_sba might be missing in most of the cases, so the template is coded as "gen c_sba = .". However, for this Angola 2006-07 MIS survey, the c_sba data is available according to the public data. The quality checking file column value_dhs is the publicly available indicator statistics generated by the USAID, which conducted the DHS. Hope my clarification makes sense to you.

Thank you @wengxyu1030 @robin-wang for your kind clarification and suggestion! I will check it again.

**Comment by jianingwwww** [comment]
Hi @wengxyu1030, I have made new changes to generate c_sba. Hope it runs well. (The quality control result shows a flag on the value of c_sba, and I am not sure whether this degree of deviation means too off from public data? I checked the data and there doesn't seem to be anything abnormal.)

**Comment by wengxyu1030** [comment]
image
Thanks @imarabbit , the code seems correct and you have specified the skilled health provider identification in the issue #3 https://github.com/wengxyu1030/MIS/issues/3. I hereby merge it to the master file.

**Pull request merged**
